### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by rehborn** [hydro-app/hydro-app#1]
- [ ] add README
- [ ] add LICENSE
- [ ] add keyboard shortcuts
- [ ] update reminders (add request permissions, title update, dismiss, ignore if recently)
- [ ] update theme settings (utilize browsers prefers-color-schema)
- [ ] automatically change day
- [ ] link back to github repository
- [ ] i18n support
- [ ] weekly stats
- [ ] add more svg shapes
